---
abstract: 'An atompub server that supports the message queue/bus model.'
author:
  - 'Naveed Massjouni <naveed.massjouni@rackspace.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AtomMQ
requires:
  Atompub: 0
  Capture::Tiny: 0
  DBD::SQLite: 0
  DBIx::Class: 0.08115
  Dancer: 1.2002
  Dancer::Plugin::DBIC: 0.1504
  SQL::Translator: 0.11006
  UUID::Tiny: 0.02
  XML::Atom: 0
  XML::XPath: 0
resources:
  bugtracker: http://github.com/ironcamel/AtomMQ/issues
  repository: git://github.com/ironcamel/AtomMQ.git
version: 1.0300
